### ISSUE TITLE
Code  Error in Version 2.0.1

### ISSUE THREAD

**Issue by yyrdl** [cinder92/react-native-get-music-files#26]
Error in `index.js`

Code:
```js
const MusicFiles = {
    getAll(options){

        return new Promise((resolve, reject) => {

            if(Platform.OS === "android"){
                RNReactNativeGetMusicFiles.getAll(options,(response) => {
                    resolve(response);
                },(error) => {
                    reject(error);
                });
            }else{
                RNReactNativeGetMusicFiles.getAll(options, (tracks) => {
                    if(tracks.length > 0){
                        resolve(tracks);
                    }else{
                        reject(false);
                    }
                });
            }

        });

    }
}
```
You should swap the last two param of function  `RNReactNativeGetMusicFiles.getAll`. 

The definition  of RNReactNativeGetMusicFiles.getAll  is 

` public void getAll(ReadableMap options, final Callback errorCallback, final Callback successCallback)`

But the master branch of the repo is right....

**Comment by cinder92** [comment]
Thanks, I will fix it

**Comment by cinder92** [comment]
fixed in v2.1.0

**Comment by yyrdl** [comment]
thanks for your work :)

**Comment by codal-mpawar** [comment]
@cinder92 @yyrdl I am still facing an issue on the iOS platform let me know the solution is urgent.
I am using your latest version.
